### ISSUE TITLE
Bigquery support

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpm#19]
More specifically, given a data package convert resource schemas to bigquery form and/or upload all my data to bigquery for me ...

**Comment by pwalsh** [comment]
@rgrp given the [python implementation of the same](https://github.com/frictionlessdata/jsontableschema-bigquery-py), I'm wondering what you currently think of this. My thoughts are that yes, as dpm will be the official cli for data package stuff, it is worth porting the storage impl we did for python to here to, and using that pattern to implement BQ and other backends on demand.

**Comment by rgrp** [comment]
WONTFIX.

Doubtful this needs to be a core command -- more a patter or a plugin (if we had such things). So will close as wontfix for now.
