### ISSUE TITLE
Proposed Revisions

### ISSUE THREAD

**Issue by waylonflinn** [frictionlessdata/dpm#57]
@danfowler requested that I get more involved here. I caution him to be more careful what he asks for, in future.

This is a short list of items that have come up as I worked through needs at [dataship](https://dataship.io). Some involve changes for consistency, some are extensions.

### `sources`
For consistency rename `web` to `url`. This is about using a consistent property name for URLs.
Same thing likely applies to `author` and `contributor`, but I haven't done anything with those yet.

### `homepage` (string) -> `web` (object)

Change the homepage string to an object with a `name` property and a `url` property.  Also rename it from `homepage` to `web`. This came up in the context of hosting datapackages for media companies (specifically five thirty eight). This is used to link back to a page published on their site that highlights the data. Likely to come up a lot when serving this segment.

### `license` -> `licenses`
This needed to be an array for us.

### `created`
This new field is an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string describing when the datapackage was created, in UTC. 
`2014-04-14T15:21:00.000Z`

Happy to discuss any of these further.

**Comment by danfowler** [comment]
Thanks @waylonflinn!  These all seem sensible.  In fact, the `license` -> `licenses` change is already pretty much agreed: https://github.com/frictionlessdata/specs/issues/236

Can we bring the rest of these issues over to the https://github.com/frictionlessdata/specs/issues issue tracker?  You can raise them individually.  Thanks again, and this is a super great time to raise them!

**Comment by danfowler** [comment]
This issue was moved to frictionlessdata/specs#298
